name: Fuzz
on:
  push:
    branches:
    - master

jobs:
  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    env:
      FUZZIT_API_KEY: ${{ secrets.FUZZIT_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Install the Fuzzit CLI
      run: |
        wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/latest/download/fuzzit_Linux_x86_64
        chmod a+x fuzzit
    - name: Install go-fuzz-build
      run: go get -u github.com/dvyukov/go-fuzz/go-fuzz-build
    - name: Rename package main
      run: sed -i "s|package main|package _main|g" ./cmd/wordrow/*.go
    - name: Build fuzz target
      run: make fuzz-build PKG=cmd/wordrow
    - name: Push fuzz target
      run: |
        ./fuzzit create target --skip-if-exists wordrow
        ./fuzzit create job --engine go-fuzz --type fuzzing ericcornelissen-gh/wordrow ./cmd/wordrow/_main-fuzz.zip
